
Currently Loaded Modules:
  1) python3.10-anaconda/2023.03   4) cupti/11.8.0    7) numpy/1.22.3
  2) cuda/11.8.0                   5) gcc/10.3.0      8) pytorch/2.0.1
  3) cudnn/11.8-v8.7.0             6) python/3.10.4

 

0it [00:00, ?it/s]0it [00:02, ?it/s]
Traceback (most recent call last):
  File "/home/wenleyan/projects/MotionBERT/train.py", line 396, in <module>
    train_with_config(args, opts)
  File "/home/wenleyan/projects/MotionBERT/train.py", line 343, in train_with_config
    train_epoch(args, model_pos, train_loader_3d, losses, optimizer, has_3d=True, has_gt=True) 
  File "/home/wenleyan/projects/MotionBERT/train.py", line 179, in train_epoch
    predicted_3d_pos = model_pos(batch_input)    # (N, T, 17, 3)
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wenleyan/projects/MotionBERT/lib/model/DSTformer.py", line 342, in forward
    x_ts = blk_ts(x, F)
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wenleyan/projects/MotionBERT/lib/model/DSTformer.py", line 249, in forward
    x = x + self.drop_path(self.mlp_s(self.norm2_s(x)))
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wenleyan/projects/MotionBERT/lib/model/DSTformer.py", line 83, in forward
    x = self.fc2(x)
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sw/pkgs/arc/python/3.10.4/pytorch/2.0.1/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 260.00 MiB (GPU 0; 15.77 GiB total capacity; 14.33 GiB already allocated; 1.12 MiB free; 14.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
